db:
  image: mongo
  ports:
    - "27017:27017"

app:
  build: .
  command: make start/docker
  volumes:
    - .:/suite
  ports:
    - "5555:5555"
  links:
    - db
  environment:
    MONGODB_URI: mongodb://db:27017/brigadehub
    GITHUB_ID:
    GITHUB_SECRET:
